create table if not exists user_readings (
  id bigint generated by default as primary key,
  user_id text not null,
  chart_data jsonb,
  reading_text text,
  provider text,
  updated_at timestamptz default now()
);
create unique index if not exists idx_user_readings_user_id on user_readings(user_id);
alter table user_readings enable row level security;
create policy "user_own_readings" on user_readings for select using (auth.uid()::text = user_id);
